export const EMPTY_COUNTRY_ID = 0;

export const STATIC_LABELS_BY_LANG = {
    'rus': {
        'beach_line': 'Линия пляжа',
        'location':   'Расположение',
        'beach':      'Пляж',
        'main':       'Главное',
        'beach_type': 'Тип пляжа',
        'child':      'Для детей',
        'hotel':      'Услуги в отеле',
        'room':       'Удобства в номерах',
        'sport':      'Развлечения и спорт',
        'recommend':  'Отели с рекомендацией',
    },
    'ukr': {
        'beach_line': 'Лінія пляжу',
        'location':   'Розташування',
        'beach':      'Пляж',
        'main':       'Головне',
        'beach_type': 'Тип пляжу',
        'child':      'Для дітей',
        'hotel':      'Послуги в готелі',
        'room':       'Зручності у номерах',
        'sport':      'Розваги та спорт',
        'recommend':  'Готелі з рекомендацією',
    },
    'en': {
        'beach_line': 'Beach line',
        'location':   'Location',
        'beach':      'Beach',
        'main':       'Main',
        'beach_type': 'Beach type',
        'child':      'For kids',
        'hotel':      'Hotel facilities',
        'room':       'Room amenities',
        'sport':      'Entertainment and sports',
        'recommend':  'Hotels with recommendation',
    },
    'pl': {
        'beach_line': 'Linia brzegowa',
        'location':   'Lokalizacja',
        'beach':      'Plaża',
        'main':       'Główne',
        'beach_type': 'Typ plaży',
        'child':      'Dla dzieci',
        'hotel':      'Usługi hotelowe',
        'room':       'Udogodnienia w pokoju',
        'sport':      'Rozrywka i sport',
        'recommend':  'Hotele z rekomendacją',
    },
    'ro': {
        'beach_line': 'Linia plajei',
        'location':   'Locație',
        'beach':      'Plajă',
        'main':       'Principal',
        'beach_type': 'Tipul plajei',
        'child':      'Pentru copii',
        'hotel':      'Servicii în hotel',
        'room':       'Facilități în camere',
        'sport':      'Divertisment și sport',
        'recommend':  'Hoteluri recomandate',
    },
};
